name: Build and Test

on:
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Austral compiler
        run: curl -o austral https://github.com/austral/austral/releases/download/v0.0.2/austral-linux

      - name: Install Austral compiler
        run: sudo install -m 755 austral /usr/local/bin/austral

      - name: Build standard library unit tests
        run: make test_bin

      - name: Run tests
        run: ./test_bin
