name: Build and Test

on:
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install make dune ppx_deriving ounit2 menhir

      - name: Clone Austral repo
        run: git clone git@github.com:austral/austral.git

      - name: Build Austral
        run: cd austral && make && sudo make install && cd ..

      - name: Build standard library unit tests
        run: make test_bin

      - name: Run tests
        run: ./test_bin
