name: Build and Test

on:
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Austral compiler
        run: curl -o austral -L "https://github.com/austral/austral/releases/download/v0.0.2/austral-linux"

      - name: Make Austral compiler executable
        run: chmod +x austral

      - name: Build standard library unit tests
        run: make test_bin 'AUSTRAL=./austral'

      - name: Run tests
        run: ./test_bin
